[CI] Enhance comments in "managed" github issues
Till now the CI would automatically open and close issues based on the
CI results, providing just a link to the failing or successful run.

This PR aims to add a bit more context by showing what jobs failed, in
which step, and some filtered output from the logs. To filter the logs
for only related to the corresponding GitHub issue workflow jobs one can
define a "Job Filter" in the GitHub issue's description. E.g.:

Job Filter: Q main G 22 latest

will only filter and report logs from jobs containing
"Q main G 22 latest" in their name, e.g.,
"Q main G 22 latest / Q IT Misc2"

The resulting comment in the GitHub issue will look like this:

The build is still failing!

Failed jobs:
* [Q main G 22 latest / Q IT Data5](https://github.com/graalvm/mandrel/actions/runs/7108970473/job/19353780171)
  * Step: Build with Maven
    Filtered logs:
```
2023-12-06T02:34:24.6847074Z org.opentest4j.AssertionFailedError: Type 'com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl' was found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20231206_023237.txt
2023-12-06T02:38:57.0457755Z Error: Class initialization of io.vertx.pgclient.impl.codec.DataTypeCodec failed. Use the option
2023-12-06T02:43:25.9882325Z Error: Class initialization of io.vertx.pgclient.impl.codec.DataTypeCodec failed. Use the option
2023-12-06T02:46:22.4042108Z [INFO] Quarkus - Integration Tests - JPA - PostgreSQL ..... FAILURE [03:57 min]
2023-12-06T02:46:22.4044859Z [INFO] Quarkus - Integration Tests - Hibernate Reactive - PostgreSQL FAILURE [01:03 min]
2023-12-06T02:46:22.4047360Z [INFO] Quarkus - Integration Tests - Reactive Pg Client ... FAILURE [ 52.547 s]
```
* [Q main G 22 latest / Q IT Data7](https://github.com/graalvm/mandrel/actions/runs/7108970473/job/19353780524)
  * Step: Build with Maven
    Filtered logs:
```
2023-12-06T02:35:15.1577013Z 2023-12-06 02:35:15,119 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (vert.x-eventloop-thread-0) SQL Error: -204, SQLState: 42704
2023-12-06T02:35:15.1586877Z 2023-12-06 02:35:15,123 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (vert.x-eventloop-thread-0) SQL Error: -204, SQLState: 42704
2023-12-06T02:48:07.0671437Z Error: Class initialization of io.vertx.pgclient.impl.codec.DataTypeCodec failed. Use the option
2023-12-06T02:49:46.2298413Z Error: Class initialization of io.vertx.pgclient.impl.codec.DataTypeCodec failed. Use the option
2023-12-06T02:49:46.2423648Z Error: Class initialization of io.vertx.pgclient.impl.codec.DataTypeCodec failed. This error is reported at image build time because class io.vertx.pgclient.impl.codec.DataTypeCodec is registered for linking at image build time by command line and command line. Use the option
2023-12-06T02:49:46.2512671Z Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.vertx.pgclient.impl.codec.DataTypeCodec
2023-12-06T02:49:46.2517627Z Caused by: java.lang.ExceptionInInitializerError: Exception java.time.format.DateTimeParseException: Text '4714-11-24 00:00:00 BC' could not be parsed at index 20 [in thread "ForkJoinPool.commonPool-worker-2"]
2023-12-06T03:00:59.9015846Z [INFO] Quarkus - Integration Tests - Hibernate Reactive with Panache FAILURE [01:27 min]
2023-12-06T03:00:59.9016990Z [INFO] Quarkus - Integration Tests - Hibernate Reactive with Panache and Kotlin FAILURE [01:39 min]
```
* [Q main G 22 latest / Q IT Security3](https://github.com/graalvm/mandrel/actions/runs/7108970473/job/19353781553)
  * Step: Build with Maven
    Filtered logs:
```
2023-12-06T02:48:26.4464579Z Error: Class initialization of io.vertx.pgclient.impl.codec.DataTypeCodec failed. Use the option
2023-12-06T02:55:45.1948764Z [INFO] Quarkus - Integration Tests - Security WebAuthn .... FAILURE [01:27 min]
```
* [Q main G 22 latest / Q IT Misc4](https://github.com/graalvm/mandrel/actions/runs/7108970473/job/19353782619)
  * Step: Build with Maven
    Filtered logs:
```
2023-12-06T03:23:28.2319284Z Error: Class initialization of com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl failed. Use the option
2023-12-06T03:23:28.3140196Z [INFO] Quarkus - Integration Tests - JAXP ................. FAILURE [ 18.185 s]
```
* [Q main G 22 latest / Q IT AWT, ImageIO and Java2D](https://github.com/graalvm/mandrel/actions/runs/7108970473/job/19353783389)
  * Step: Build with Maven
    Filtered logs:
```
2023-12-06T02:25:34.9321321Z Error: Error loading a referenced type: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method jdk.internal.loader.NativeLibrary.findEntry0(long, String) is reachable
2023-12-06T02:28:01.6411073Z [INFO] Quarkus - Integration Tests - AWT .................. FAILURE [01:27 min]
```

Link to latest CI run: https://github.com/graalvm/mandrel/actions/runs/7108970473